#!/bin/bash

set -e

heading () {
	echo ""
	echo "########## $1 ##########"
	echo ""
}

cd /datingnode-ansible

for arg in "$@"; do

	case "$arg" in

	(init-system)

		if ! test -f /etc/dnode-update-flag; then

			heading "Updating system packages"

			cat <<-EOF >/etc/apt/apt.conf.d/01proxy
				Acquire::http::Proxy "http://172.17.42.1:3142";
			EOF

			apt-get update
			apt-get dist-upgrade --yes

			touch /etc/dnode-update-flag

		fi

		;;

	(init-ansible)

		if ! test -f /etc/dnode-ansible-flag; then

			heading "Installing required packages for ansible"

			apt-get install --yes aptitude python-dev python-pip
			pip install paramiko PyYAML jinja2 httplib2

			touch /etc/dnode-ansible-flag

		fi

		;;

	(*)

		if ! test "$ANSIBLE_HOME"; then

			heading "Initialising ansible environment"

			source ansible/hacking/env-setup

		fi

		heading "Applying ansible role $arg"

		ansible-playbook \
			-c local \
			-i local \
			misc/apply-role.yml \
			-e "role=$arg"

		;;

	esac

done
