#!/bin/bash

set -e

BINARY="/usr/bin/memcached"
USER="memcache"
LOG="/var/log/memcached.log"
MAX_MEMORY="{{ 4 * 1024 }}"
MAX_CONNECTIONS="1024"
LISTEN_IP="0.0.0.0"
LISTEN_PORT="11211"

exec >>"$LOG" 2>&1

exec "$BINARY" \
	-d \
	-m "$MAX_MEMORY" \
	-p "$LISTEN_PORT" \
	-u "$USER" \
	-l "$LISTEN_IP" \
	-c "$MAX_CONNECTIONS"
