#!/bin/bash

set -e

cd /root/datingnode-ansible

source ansible/hacking/env-setup

ansible-playbook \
	--connection local \
	--inventory local \
	--extra-vars @/vhost-proxy/runtime-config \
	--extra-vars @/vhost-proxy/parent-config \
	--extra-vars "role=config-vhost-proxy" \
	misc/apply-role.yml
