#!/bin/bash

# initialise bridge tables

	ebtables --table "nat" --flush
	ebtables --table "nat" --delete-chain

	ebtables --table "nat" --policy "PREROUTING" "ACCEPT"
	ebtables --table "nat" --policy "POSTROUTING" "ACCEPT"
	ebtables --table "nat" --policy "OUTPUT" "ACCEPT"

# masquerade mac address for failover addresses

	{% for other_host_name in groups ['rocket-hz-vm'] %}
	{% set other_host = hostvars [other_host_name] %}
	{% if other_host.identity.parent == identity_name
		and 'failover' in other_host %}

		{% for failover_address in []
			| union (other_host.failover.primary | default ([]))
			| union (other_host.failover.backup | default ([]))
		%}

			ebtables \
				--table "nat" \
				--append "PREROUTING" \
				--in-interface "eth0" \
				--protocol "ipv4" \
				--ip-destination "{{ failover_address }}" \
				--jump dnat \
				--to-destination "{{ other_host.public.mac }}"

			ebtables \
				--table "nat" \
				--append "POSTROUTING" \
				--out-interface "eth0" \
				--protocol "ipv4" \
				--ip-source "{{ failover_address }}" \
				--jump snat \
				--to-source "{{ other_host.public.mac }}"

		{% endfor %}

	{% endif %}
	{% endfor %}

# ex: noet ts=4 filetype=bash
