#!/bin/bash

trap 'exit 1' INT

for domain in $(cat $HOME/datingnode-domain-list); do

	if test \
		-f secret-plain/ssl/$domain.cert -a \
		-f secret-plain/ssl/$domain.key; then
		continue
	fi

	tools/certificate-authority export \
		--authority rocketware \
		--common-name $domain \
		--full-certificate-chain secret-plain/ssl/$domain.cert \
		--private-key secret-plain/ssl/$domain.key

done
