#!/usr/bin/env python

import json
import requests

amazon_ip_ranges = json.loads (
	requests.get ("https://ip-ranges.amazonaws.com/ip-ranges.json").text)

cloudfront_prefixes = [
	prefix ["ip_prefix"]
	for prefix in amazon_ip_ranges ["prefixes"]
	if prefix ["service"] == "CLOUDFRONT"
]

for prefix in cloudfront_prefixes:
	print prefix
