#!/bin/bash

function setup-ansible {

	heading "Perfoming datingnode ansible setup"

	subheading "Cloning datingnode-ansible"

	ssh "echo \"$GITHUB_KEY\" >> \".ssh/known_hosts\""
	ssh "rm -rf \"datingnode-ansible\""
	ssh "git clone \"$DATINGNODE_ANSIBLE\""
	ssh "mkdir \"\$HOME/datingnode-ansible/config\""

	subheading "Building third party components"

	ssh "cd \"datingnode-ansible\"; scripts/setup-project build"

	subheading "Create devops config (overrides)"

	DEVBOX_IP=$(getent hosts "$NAME.local" | cut -d' ' -f1)

	template "overrides" >"$TEMP/overrides.yml"

	scp_send \
		"$TEMP/overrides.yml" \
		"datingnode-ansible/config/overrides-bootstrap.yml"

}

function setup-bootstrap {

	heading "Perfom datingnode bootstrap setup"

	subheading "Run bootstrap"

	ssh $(
		echo "cd \"\$HOME/datingnode-ansible\";"
		echo "scripts/bootstrap \"$DEPLOYMENT\";"
	)

}

# ex: noet ts=4 filetype=bash
