#!/bin/bash

set -euf -o pipefail

if test "$#" != "1"; then
	echo "Syntax: $0 CLUSTER" >&2
	exit 1
fi

cluster="$1"
hostname="$(hostname --short)"
ip_address="$(dig +short $hostname)"
dev_user="$USER"
dev_group="$USER"

resource_names=(
	"admin-group/admins"
	"admin-user/admin"
	"host/${hostname}"
	"cluster/master"
	"cluster/${cluster}"
	"host/${cluster}-database-1"
	"host/${cluster}-web-application-1"
	"host/${cluster}-vhost-proxy-1"
	"host/${cluster}-memcache-1"
	"host/${cluster}-icinga-1"
)

for resource_name in "${resource_names[@]}"; do

	./datingnode-local resource remove \
		--name "$resource_name"

done

# ex: noet ts=4 filetype=sh
