#!/usr/bin/env python

import argparse
import itertools
import sys

import dnode
import dnode.authority
import dnode.data

def main ():

	parser = argparse.ArgumentParser ()
	sub_parsers = parser.add_subparsers ()

	# ---------- create

	parser_create = sub_parsers.add_parser ("create")
	parser_create.set_defaults (func = do_create)

	parser_create.add_argument (
		"--database",
		required = True)

	# ---------- request

	parser_request = sub_parsers.add_parser ("request")
	parser_request.set_defaults (func = do_request)

	parser_request.add_argument (
		"--database",
		required = True)

	parser_request.add_argument (
		"--common-name",
		required = True)

	# ---------- cancel

	parser_cancel = sub_parsers.add_parser ("cancel")
	parser_cancel.set_defaults (func = do_cancel)

	parser_cancel.add_argument (
		"--database",
		required = True)

	parser_cancel.add_argument (
		"--common-name",
		required = True)

	# ---------- etc

	args = parser.parse_args ()
	args.func (args)

def do_create (args):

	dnode_client = dnode.get_client ()

	database = dnode.certificate.Database (
		dnode_client,
		"/certificate/" + args.database,
		dnode.certificate_data)

	if database.exists ():

		print "Certificate database already exists"

		return

	database.create ()

	print "Certificate database created"

def do_request (args):

	dnode_client = dnode.get_client ()

	database = dnode.certificate.Database (
		dnode_client,
		"/certificate/" + args.database,
		dnode.certificate_data)

	success, csr, key = database.request (
		args.common_name)

	if success:

		print "Request created for " + args.common_name

		sys.exit (0)

	else:

		print "There is already a request pending for " + args.common_name

		sys.exit (1)

def do_cancel (args):

	dnode_client = dnode.get_client ()

	database = dnode.certificate.Database (
		dnode_client,
		"/certificate/" + args.database,
		dnode.certificate_data)

	success = database.cancel (
		args.common_name)

	if success:

		print "Request cancelled for " + args.common_name

		sys.exit (0)

	else:

		print "There is no request pending for " + args.common_name

		sys.exit (1)
main ()
